name: connect
description: "A new Nowa project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  nowa_runtime: ^0.1.3
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  dio: ^5.5.0+1
  zego_uikit_prebuilt_call: ^4.22.2
  zego_uikit_signaling_plugin: ^2.8.20
  google_sign_in: ^6.2.1
  http: ^1.2.0
  jwt_decoder: ^2.0.1
  razorpay_flutter: 1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png